// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: internal/proto/sync.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType identifies the type of message being sent.
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED       MessageType = 0
	MessageType_MESSAGE_TYPE_HANDSHAKE         MessageType = 1
	MessageType_MESSAGE_TYPE_HANDSHAKE_ACK     MessageType = 2
	MessageType_MESSAGE_TYPE_MANIFEST_REQUEST  MessageType = 3
	MessageType_MESSAGE_TYPE_MANIFEST_RESPONSE MessageType = 4
	MessageType_MESSAGE_TYPE_CHUNK_REQUEST     MessageType = 5
	MessageType_MESSAGE_TYPE_CHUNK_RESPONSE    MessageType = 6
	MessageType_MESSAGE_TYPE_ERROR             MessageType = 7
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "MESSAGE_TYPE_HANDSHAKE",
		2: "MESSAGE_TYPE_HANDSHAKE_ACK",
		3: "MESSAGE_TYPE_MANIFEST_REQUEST",
		4: "MESSAGE_TYPE_MANIFEST_RESPONSE",
		5: "MESSAGE_TYPE_CHUNK_REQUEST",
		6: "MESSAGE_TYPE_CHUNK_RESPONSE",
		7: "MESSAGE_TYPE_ERROR",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED":       0,
		"MESSAGE_TYPE_HANDSHAKE":         1,
		"MESSAGE_TYPE_HANDSHAKE_ACK":     2,
		"MESSAGE_TYPE_MANIFEST_REQUEST":  3,
		"MESSAGE_TYPE_MANIFEST_RESPONSE": 4,
		"MESSAGE_TYPE_CHUNK_REQUEST":     5,
		"MESSAGE_TYPE_CHUNK_RESPONSE":    6,
		"MESSAGE_TYPE_ERROR":             7,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_sync_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_internal_proto_sync_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_sync_proto_rawDescGZIP(), []int{0}
}

// Envelope wraps all messages with type and optional request ID for correlation.
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=p2psync.MessageType" json:"type,omitempty"`
	RequestId     uint64                 `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // For request/response correlation
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                       // Serialized inner message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_internal_proto_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *Envelope) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Handshake is sent when a peer initiates connection.
type Handshake struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Protocol version for compatibility checking
	ProtocolVersion uint32 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// SHA-256 fingerprint of peer's TLS certificate (32 bytes)
	CertFingerprint []byte `protobuf:"bytes,2,opt,name=cert_fingerprint,json=certFingerprint,proto3" json:"cert_fingerprint,omitempty"`
	// Human-readable peer name (optional)
	PeerName string `protobuf:"bytes,3,opt,name=peer_name,json=peerName,proto3" json:"peer_name,omitempty"`
	// Capabilities bitmap for feature negotiation
	Capabilities uint64 `protobuf:"varint,4,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Current Merkle root hash of peer's tracked directory
	MerkleRoot []byte `protobuf:"bytes,5,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	// Number of files tracked
	FileCount uint64 `protobuf:"varint,6,opt,name=file_count,json=fileCount,proto3" json:"file_count,omitempty"`
	// Total size in bytes
	TotalSize     uint64 `protobuf:"varint,7,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	mi := &file_internal_proto_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_proto_rawDescGZIP(), []int{1}
}

func (x *Handshake) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Handshake) GetCertFingerprint() []byte {
	if x != nil {
		return x.CertFingerprint
	}
	return nil
}

func (x *Handshake) GetPeerName() string {
	if x != nil {
		return x.PeerName
	}
	return ""
}

func (x *Handshake) GetCapabilities() uint64 {
	if x != nil {
		return x.Capabilities
	}
	return 0
}

func (x *Handshake) GetMerkleRoot() []byte {
	if x != nil {
		return x.MerkleRoot
	}
	return nil
}

func (x *Handshake) GetFileCount() uint64 {
	if x != nil {
		return x.FileCount
	}
	return 0
}

func (x *Handshake) GetTotalSize() uint64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

// HandshakeAck acknowledges a handshake and provides peer info.
type HandshakeAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether handshake was accepted
	Accepted bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// Reason for rejection (if not accepted)
	RejectionReason string `protobuf:"bytes,2,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	// SHA-256 fingerprint of this peer's TLS certificate
	CertFingerprint []byte `protobuf:"bytes,3,opt,name=cert_fingerprint,json=certFingerprint,proto3" json:"cert_fingerprint,omitempty"`
	// Peer's name
	PeerName string `protobuf:"bytes,4,opt,name=peer_name,json=peerName,proto3" json:"peer_name,omitempty"`
	// Peer's current Merkle root
	MerkleRoot []byte `protobuf:"bytes,5,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	// Negotiated protocol version
	ProtocolVersion uint32 `protobuf:"varint,6,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HandshakeAck) Reset() {
	*x = HandshakeAck{}
	mi := &file_internal_proto_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeAck) ProtoMessage() {}

func (x *HandshakeAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeAck.ProtoReflect.Descriptor instead.
func (*HandshakeAck) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_proto_rawDescGZIP(), []int{2}
}

func (x *HandshakeAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HandshakeAck) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *HandshakeAck) GetCertFingerprint() []byte {
	if x != nil {
		return x.CertFingerprint
	}
	return nil
}

func (x *HandshakeAck) GetPeerName() string {
	if x != nil {
		return x.PeerName
	}
	return ""
}

func (x *HandshakeAck) GetMerkleRoot() []byte {
	if x != nil {
		return x.MerkleRoot
	}
	return nil
}

func (x *HandshakeAck) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

// ManifestRequest requests the Merkle tree manifest from a peer.
type ManifestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: request only a subtree starting at this path
	SubtreePath string `protobuf:"bytes,1,opt,name=subtree_path,json=subtreePath,proto3" json:"subtree_path,omitempty"`
	// Maximum depth to return (-1 for unlimited)
	MaxDepth int32 `protobuf:"varint,2,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`
	// If true, include chunk hashes in file nodes
	IncludeChunks bool `protobuf:"varint,3,opt,name=include_chunks,json=includeChunks,proto3" json:"include_chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestRequest) Reset() {
	*x = ManifestRequest{}
	mi := &file_internal_proto_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestRequest) ProtoMessage() {}

func (x *ManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestRequest.ProtoReflect.Descriptor instead.
func (*ManifestRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_proto_rawDescGZIP(), []int{3}
}

func (x *ManifestRequest) GetSubtreePath() string {
	if x != nil {
		return x.SubtreePath
	}
	return ""
}

func (x *ManifestRequest) GetMaxDepth() int32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

func (x *ManifestRequest) GetIncludeChunks() bool {
	if x != nil {
		return x.IncludeChunks
	}
	return false
}

// ManifestResponse contains the Merkle tree structure.
type ManifestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Root node of the tree/subtree
	Root *ManifestNode `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	// Total number of nodes in response
	NodeCount     uint64 `protobuf:"varint,2,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestResponse) Reset() {
	*x = ManifestResponse{}
	mi := &file_internal_proto_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestResponse) ProtoMessage() {}

func (x *ManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestResponse.ProtoReflect.Descriptor instead.
func (*ManifestResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_proto_rawDescGZIP(), []int{4}
}

func (x *ManifestResponse) GetRoot() *ManifestNode {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *ManifestResponse) GetNodeCount() uint64 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

// ManifestNode represents a single node in the Merkle tree.
type ManifestNode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// File or directory name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// True if directory, false if file
	IsDir bool `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	// SHA-256 hash of this node
	Hash []byte `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	// File permissions
	Mode uint32 `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
	// Size in bytes
	Size uint64 `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	// Children (for directories)
	Children []*ManifestNode `protobuf:"bytes,6,rep,name=children,proto3" json:"children,omitempty"`
	// Chunk hashes (for files, if requested)
	Chunks        [][]byte `protobuf:"bytes,7,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestNode) Reset() {
	*x = ManifestNode{}
	mi := &file_internal_proto_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestNode) ProtoMessage() {}

func (x *ManifestNode) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestNode.ProtoReflect.Descriptor instead.
func (*ManifestNode) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_proto_rawDescGZIP(), []int{5}
}

func (x *ManifestNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ManifestNode) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *ManifestNode) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *ManifestNode) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *ManifestNode) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ManifestNode) GetChildren() []*ManifestNode {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *ManifestNode) GetChunks() [][]byte {
	if x != nil {
		return x.Chunks
	}
	return nil
}

// ChunkRequest requests one or more chunks by hash.
type ChunkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hashes of requested chunks (can batch multiple)
	ChunkHashes [][]byte `protobuf:"bytes,1,rep,name=chunk_hashes,json=chunkHashes,proto3" json:"chunk_hashes,omitempty"`
	// Priority hint (higher = more urgent)
	Priority      uint32 `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkRequest) Reset() {
	*x = ChunkRequest{}
	mi := &file_internal_proto_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkRequest) ProtoMessage() {}

func (x *ChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkRequest.ProtoReflect.Descriptor instead.
func (*ChunkRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_proto_rawDescGZIP(), []int{6}
}

func (x *ChunkRequest) GetChunkHashes() [][]byte {
	if x != nil {
		return x.ChunkHashes
	}
	return nil
}

func (x *ChunkRequest) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// ChunkResponse returns requested chunks.
type ChunkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The chunks being returned
	Chunks []*Chunk `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	// Hashes that were not found
	NotFound      [][]byte `protobuf:"bytes,2,rep,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkResponse) Reset() {
	*x = ChunkResponse{}
	mi := &file_internal_proto_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkResponse) ProtoMessage() {}

func (x *ChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkResponse.ProtoReflect.Descriptor instead.
func (*ChunkResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_proto_rawDescGZIP(), []int{7}
}

func (x *ChunkResponse) GetChunks() []*Chunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *ChunkResponse) GetNotFound() [][]byte {
	if x != nil {
		return x.NotFound
	}
	return nil
}

// Chunk represents a single content-addressed data block.
type Chunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SHA-256 hash of the chunk data
	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	// Actual chunk data
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Size of data (for validation)
	Size          uint32 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_internal_proto_sync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_proto_rawDescGZIP(), []int{8}
}

func (x *Chunk) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Chunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Chunk) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// ErrorMessage reports an error to the peer.
type ErrorMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Error code
	Code uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// Human-readable error message
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Request ID that caused the error (if applicable)
	RequestId     uint64 `protobuf:"varint,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMessage) Reset() {
	*x = ErrorMessage{}
	mi := &file_internal_proto_sync_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessage) ProtoMessage() {}

func (x *ErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessage.ProtoReflect.Descriptor instead.
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_proto_rawDescGZIP(), []int{9}
}

func (x *ErrorMessage) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorMessage) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

var File_internal_proto_sync_proto protoreflect.FileDescriptor

const file_internal_proto_sync_proto_rawDesc = "" +
	"\n" +
	"\x19internal/proto/sync.proto\x12\ap2psync\"m\n" +
	"\bEnvelope\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.p2psync.MessageTypeR\x04type\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\x04R\trequestId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\x81\x02\n" +
	"\tHandshake\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12)\n" +
	"\x10cert_fingerprint\x18\x02 \x01(\fR\x0fcertFingerprint\x12\x1b\n" +
	"\tpeer_name\x18\x03 \x01(\tR\bpeerName\x12\"\n" +
	"\fcapabilities\x18\x04 \x01(\x04R\fcapabilities\x12\x1f\n" +
	"\vmerkle_root\x18\x05 \x01(\fR\n" +
	"merkleRoot\x12\x1d\n" +
	"\n" +
	"file_count\x18\x06 \x01(\x04R\tfileCount\x12\x1d\n" +
	"\n" +
	"total_size\x18\a \x01(\x04R\ttotalSize\"\xe9\x01\n" +
	"\fHandshakeAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12)\n" +
	"\x10rejection_reason\x18\x02 \x01(\tR\x0frejectionReason\x12)\n" +
	"\x10cert_fingerprint\x18\x03 \x01(\fR\x0fcertFingerprint\x12\x1b\n" +
	"\tpeer_name\x18\x04 \x01(\tR\bpeerName\x12\x1f\n" +
	"\vmerkle_root\x18\x05 \x01(\fR\n" +
	"merkleRoot\x12)\n" +
	"\x10protocol_version\x18\x06 \x01(\rR\x0fprotocolVersion\"x\n" +
	"\x0fManifestRequest\x12!\n" +
	"\fsubtree_path\x18\x01 \x01(\tR\vsubtreePath\x12\x1b\n" +
	"\tmax_depth\x18\x02 \x01(\x05R\bmaxDepth\x12%\n" +
	"\x0einclude_chunks\x18\x03 \x01(\bR\rincludeChunks\"\\\n" +
	"\x10ManifestResponse\x12)\n" +
	"\x04root\x18\x01 \x01(\v2\x15.p2psync.ManifestNodeR\x04root\x12\x1d\n" +
	"\n" +
	"node_count\x18\x02 \x01(\x04R\tnodeCount\"\xc0\x01\n" +
	"\fManifestNode\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\fR\x04hash\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\rR\x04mode\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x04R\x04size\x121\n" +
	"\bchildren\x18\x06 \x03(\v2\x15.p2psync.ManifestNodeR\bchildren\x12\x16\n" +
	"\x06chunks\x18\a \x03(\fR\x06chunks\"M\n" +
	"\fChunkRequest\x12!\n" +
	"\fchunk_hashes\x18\x01 \x03(\fR\vchunkHashes\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\rR\bpriority\"T\n" +
	"\rChunkResponse\x12&\n" +
	"\x06chunks\x18\x01 \x03(\v2\x0e.p2psync.ChunkR\x06chunks\x12\x1b\n" +
	"\tnot_found\x18\x02 \x03(\fR\bnotFound\"C\n" +
	"\x05Chunk\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x12\n" +
	"\x04size\x18\x03 \x01(\rR\x04size\"[\n" +
	"\fErrorMessage\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\x04R\trequestId*\x87\x02\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16MESSAGE_TYPE_HANDSHAKE\x10\x01\x12\x1e\n" +
	"\x1aMESSAGE_TYPE_HANDSHAKE_ACK\x10\x02\x12!\n" +
	"\x1dMESSAGE_TYPE_MANIFEST_REQUEST\x10\x03\x12\"\n" +
	"\x1eMESSAGE_TYPE_MANIFEST_RESPONSE\x10\x04\x12\x1e\n" +
	"\x1aMESSAGE_TYPE_CHUNK_REQUEST\x10\x05\x12\x1f\n" +
	"\x1bMESSAGE_TYPE_CHUNK_RESPONSE\x10\x06\x12\x16\n" +
	"\x12MESSAGE_TYPE_ERROR\x10\aB\x1eZ\x1cp2p-file-sync/internal/protob\x06proto3"

var (
	file_internal_proto_sync_proto_rawDescOnce sync.Once
	file_internal_proto_sync_proto_rawDescData []byte
)

func file_internal_proto_sync_proto_rawDescGZIP() []byte {
	file_internal_proto_sync_proto_rawDescOnce.Do(func() {
		file_internal_proto_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_sync_proto_rawDesc), len(file_internal_proto_sync_proto_rawDesc)))
	})
	return file_internal_proto_sync_proto_rawDescData
}

var file_internal_proto_sync_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_proto_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_proto_sync_proto_goTypes = []any{
	(MessageType)(0),         // 0: p2psync.MessageType
	(*Envelope)(nil),         // 1: p2psync.Envelope
	(*Handshake)(nil),        // 2: p2psync.Handshake
	(*HandshakeAck)(nil),     // 3: p2psync.HandshakeAck
	(*ManifestRequest)(nil),  // 4: p2psync.ManifestRequest
	(*ManifestResponse)(nil), // 5: p2psync.ManifestResponse
	(*ManifestNode)(nil),     // 6: p2psync.ManifestNode
	(*ChunkRequest)(nil),     // 7: p2psync.ChunkRequest
	(*ChunkResponse)(nil),    // 8: p2psync.ChunkResponse
	(*Chunk)(nil),            // 9: p2psync.Chunk
	(*ErrorMessage)(nil),     // 10: p2psync.ErrorMessage
}
var file_internal_proto_sync_proto_depIdxs = []int32{
	0, // 0: p2psync.Envelope.type:type_name -> p2psync.MessageType
	6, // 1: p2psync.ManifestResponse.root:type_name -> p2psync.ManifestNode
	6, // 2: p2psync.ManifestNode.children:type_name -> p2psync.ManifestNode
	9, // 3: p2psync.ChunkResponse.chunks:type_name -> p2psync.Chunk
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_proto_sync_proto_init() }
func file_internal_proto_sync_proto_init() {
	if File_internal_proto_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_sync_proto_rawDesc), len(file_internal_proto_sync_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_sync_proto_goTypes,
		DependencyIndexes: file_internal_proto_sync_proto_depIdxs,
		EnumInfos:         file_internal_proto_sync_proto_enumTypes,
		MessageInfos:      file_internal_proto_sync_proto_msgTypes,
	}.Build()
	File_internal_proto_sync_proto = out.File
	file_internal_proto_sync_proto_goTypes = nil
	file_internal_proto_sync_proto_depIdxs = nil
}
